#!/usr/bin/env python3
"""
evaluate_sequence_model_v13_attn.py — Phase 13
Validates the Shared Attention Hazard Engine.

Outputs diagnostic interpretations charting Hazard Curves
against Temporal Focus mapping "what the model looked at".
"""

import os, sys, json, logging
import numpy as np
import torch
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score, precision_recall_fscore_support
from train_sequence_model_v13_attn import SharedAttentionHazardEngine, get_device

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)])
logger = logging.getLogger("EvalV13")

DATA_DIR = os.path.join(os.path.dirname(__file__), "../training_data")
MODEL_DIR = os.path.join(os.path.dirname(__file__), "../models/cattle")
DISEASES = ["Infection", "HeatStress", "Mastitis", "Lameness", "Calving"]

def evaluate():
    device = get_device()
    device = torch.device("cpu") # match training
    logger.info(f"Evaluating V13 on {device}")
    
    x_path = os.path.join(DATA_DIR, "v13_X_sequences.npy")
    y_path = os.path.join(DATA_DIR, "v13_Y_targets.npy")
    
    logger.info("Loading memory mapped arrays...")
    X_mmap = np.load(x_path, mmap_mode='r')
    Y_mmap = np.load(y_path, mmap_mode='r')
    
    num_samples = len(X_mmap)
    input_dim = X_mmap.shape[2]
    
    # Needs to perfectly match the permutation seed from train_sequence_model_v13_attn.py
    np.random.seed(42)
    indices = np.random.permutation(num_samples)
    split = int(0.8 * num_samples)
    test_idx = indices[split:]
    
    logger.info("Loading trained V13 PyTorch model weights...")
    model_path = os.path.join(MODEL_DIR, "v13_attention_hazard_model.pth")
    if not os.path.exists(model_path):
        logger.error(f"Waiting for {model_path} to be generated by training...")
        return
        
    model = SharedAttentionHazardEngine(input_dim=input_dim).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()
    
    logger.info(f"Evaluating {len(test_idx)} test samples...")
    
    y_true_cls = []
    y_pred_cls = []
    
    # Diagnostics storage
    hazard_curves = []
    temporal_attentions = []
    high_risk_samples = []
    
    batch_size = 256
    with torch.no_grad():
        for i in range(0, len(test_idx), batch_size):
            batch_indices = test_idx[i:i+batch_size]
            
            x_batch = torch.tensor(X_mmap[batch_indices], dtype=torch.float32).to(device)
            y_cls_batch = Y_mmap[batch_indices, 0:5]
            
            # Use Autocast just like training!
            with torch.autocast(device_type="cpu", dtype=torch.bfloat16):
                logits_cls, preds_sev, hazard_logits, temporal_weights = model(x_batch)
                
            probs = torch.sigmoid(logits_cls).float().cpu().numpy()
            hazard_probs = torch.sigmoid(hazard_logits).float().cpu().numpy()
            attention_array = temporal_weights.float().cpu().numpy()
            
            y_true_cls.append(y_cls_batch)
            y_pred_cls.append(probs)
            
            for b_idx in range(len(batch_indices)):
                # If a massive sequence-level hazard is predicted in the next 24h
                if hazard_probs[b_idx].max() > 0.8:
                    high_risk_samples.append({
                        "sample_idx": int(batch_indices[b_idx]),
                        "disease_probs": probs[b_idx].tolist(),
                        "hazard_24h_curve": hazard_probs[b_idx].tolist(),
                        "top_attention_ticks": np.argsort(attention_array[b_idx])[-5:].tolist()
                    })
            
    Y_true = np.vstack(y_true_cls)
    Y_pred = np.vstack(y_pred_cls)
    
    metrics = {}
    
    logger.info("--- ADVERSARIAL METRICS (EXPECTED 0.88 - 0.93 AUC) ---")
    for i, disease in enumerate(DISEASES):
        t = Y_true[:, i]
        p = Y_pred[:, i]
        
        auc = roc_auc_score(t, p) if len(np.unique(t)) > 1 else 0
        
        pred_labels = (p > 0.5).astype(int)
        precision, recall, f1, _ = precision_recall_fscore_support(t, pred_labels, average='binary', zero_division=0)
        
        metrics[disease] = {
            "AUC": float(auc),
            "Precision": float(precision),
            "Recall": float(recall)
        }
        logger.info(f"{disease:10} | AUC: {auc:.4f} | Recall: {recall:.4f}")
        
    fp_rate = 1.0 - np.mean([m['Precision'] for k, m in metrics.items() if isinstance(m, dict)])
    approx_fp_week = fp_rate * 7
    logger.info(f"Target False Positives per week ~{approx_fp_week:.2f} (Adversarial Target 2-5/wk)")
    
    logger.info("--- INTERPRETABILITY: SURVIVAL HAZARD DIAGNOSTICS ---")
    if high_risk_samples:
        demo = high_risk_samples[0]
        logger.info(f"Sample {demo['sample_idx']} shows severe risk:")
        logger.info(f"   Infection Prob: {demo['disease_probs'][0]:.3f}")
        logger.info(f"   Mastitis Prob:  {demo['disease_probs'][2]:.3f}")
        logger.info(f"   24h Hazard Curve: {[round(h, 2) for h in demo['hazard_24h_curve'][:6]]} ...")
        logger.info(f"   Key Attention Ticks (Critical events): {demo['top_attention_ticks']}")
        
        # UI interpretation
        focus_hrs = [(288 - tick) / 6.0 for tick in demo['top_attention_ticks']]
        logger.info(f"   [!] UI ALERT: 'Risk rising rapidly due to biological deviations approx {[round(f,1) for f in focus_hrs]} hours ago.'")
    else:
        logger.info("No high-risk samples found in the evaluation slice.")
        
    report_path = os.path.join(DATA_DIR, "v13_interpretability_report.json")
    with open(report_path, "w") as f:
        json.dump(metrics, f, indent=2)

if __name__ == "__main__":
    evaluate()
