#!/usr/bin/env python3
"""
prepare_sequences_v11.py — Phase 12 
Feature Extraction & Multi-Head Targeting.

Merges the asynchronous `v6_sensor_raw.csv` and `v6_production_raw.csv` into a wide
sliding window sequence dataset. Computes the required ~110 physical features.
"""

import os, sys, json, logging, time
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)])
logger = logging.getLogger("PrepareV11")

DATA_DIR = os.path.join(os.path.dirname(__file__), "../training_data")
MODEL_DIR = os.path.join(os.path.dirname(__file__), "../models/cattle")

SEQ_LEN = 288  # 48 hours at 10m ticks
STRIDE = 12    # shift window 2 hours at a time during training

def build_flat_timeseries():
    logger.info("Loading V6 raw CSV dumps...")
    df_sensor = pd.read_csv(os.path.join(DATA_DIR, "v6_sensor_raw.csv"), parse_dates=["timestamp"])
    df_prod = pd.read_csv(os.path.join(DATA_DIR, "v6_production_raw.csv"), parse_dates=["timestamp"])
    
    # ── 1. ALIGN ASYNCHRONOUS STREAMS ──
    # Sensor stream is perfectly strict 10-minute intervals in the CSV
    # Production stream is 12-hour asynchronous events
    logger.info("Aligning asynchronous production and sensor streams...")
    
    df_sensor = df_sensor.sort_values(by="timestamp").reset_index(drop=True)
    df_prod = df_prod.sort_values(by="timestamp").reset_index(drop=True)
    
    # Merge As of -> Forward fill sparse production data into the high density sensor tick
    df_merged = pd.merge_asof(
        df_sensor, 
        df_prod, 
        on="timestamp", 
        by="animalId", 
        direction="backward"
    )
    
    # Fill remaining NaNs for the very beginning of the series before first milking
    df_merged["milkYield"].fillna(30.0, inplace=True)
    df_merged["feedIntake"].fillna(22.0, inplace=True)
    df_merged["conductivity"].fillna(5.0, inplace=True)
    df_merged["antibioticActive"].fillna(0, inplace=True)
    
    return df_merged

def compute_multimodal_features(df):
    logger.info("Computing 110-dimensional cross-modal biological features...")
    
    # We apply rolling windows per animal.
    # To avoid slow Pandas groupby.apply, we sort and compute globally, then mask out boundary overlaps
    df = df.sort_values(by=["animalId", "timestamp"]).reset_index(drop=True)
    
    # Base Physical Features (Signals + Env + Mgmt)
    base_cols = [
        "temperature_C", "heartRate_bpm", "respiration_bpm", "activity_index",
        "thi", "ambientTemp_C", "humidity_pct",
        "milkYield", "feedIntake", "conductivity", "antibioticActive"
    ]
    
    # ── FAST ROLLING DELTAS (6h, 12h, 24h) ──
    windows = {"6h": 36, "12h": 72, "24h": 144}
    
    for w_name, w_ticks in windows.items():
        for col in ["temperature_C", "heartRate_bpm", "respiration_bpm", "activity_index", "milkYield", "conductivity"]:
            # Mean
            df[f"{col}_mean_{w_name}"] = df.groupby("animalId")[col].transform(lambda x: x.rolling(w_ticks, min_periods=1).mean())
            # Std
            df[f"{col}_std_{w_name}"] = df.groupby("animalId")[col].transform(lambda x: x.rolling(w_ticks, min_periods=1).std().fillna(0))
            # Delta (Current - Mean)
            df[f"{col}_delta_{w_name}"] = df[col] - df[f"{col}_mean_{w_name}"]
            
    # ── ADVANCED CROSS-MODAL INDICES (Phase 12 Req) ──
    # 1. Thermal Strain Index (Heat interaction)
    # Heart rate rises drastically compared to ambient temp expectations
    df["thermal_strain_index"] = df["heartRate_bpm_delta_6h"] / (df["thi"] - 72 + 1e-5)
    
    # 2. Lameness Suppression Index
    # Severe drop in activity decoupled from THI
    df["lameness_suppression"] = (1.0 - df["activity_index"]) * (df["feedIntake"] / 22.0)
    
    # 3. Mastitis Conductivity Spike
    df["mastitis_spike_index"] = df["conductivity_delta_12h"] * (df["milkYield"] / 30.0)
    
    # 4. Fever/Infection Index (Core temp decoupled from THI)
    df["fever_decoupled"] = df["temperature_C"] - (38.5 + (0.01 * np.maximum(df["thi"]-72, 0)))
    
    # Fill remaining forward boundary NaNs generated by rolling
    df.fillna(0, inplace=True)
    
    # Gather out final feature list (approx 90-110 wide depending on the loop above)
    feature_cols = [c for c in df.columns if c not in ["animalId", "timestamp", "simulationVersion"] and not c.endswith("Binary") and c != "severityLevel"]
    
    logger.info(f"Generated {len(feature_cols)} continuous features.")
    
    # Target columns for the multiple ML heads
    target_cols = [
        "infectionBinary", "heatStressBinary", "mastitisBinary", "lamenessBinary", "calvingBinary",
        "severityLevel"
    ]
    
    return df, feature_cols, target_cols


def extract_pytorch_sequences(df, feature_cols, target_cols):
    """
    Slices the flat DB into overlapping [BATCH, 288, FEATURES] PyTorch tensors.
    """
    logger.info("Extracting PyTorch Sequence Tensors...")
    
    # Global Scale
    scaler = StandardScaler()
    df[feature_cols] = scaler.fit_transform(df[feature_cols])
    
    os.makedirs(MODEL_DIR, exist_ok=True)
    with open(os.path.join(MODEL_DIR, "v11_scalers.json"), "w") as f:
        json.dump({
            "means": scaler.mean_.tolist(),
            "scales": scaler.scale_.tolist(),
            "features": feature_cols,
            "targets": target_cols
        }, f)
        
    # Precalculate total sequences to preallocate numpy array and avoid massive list overhead
    total_seqs = 0
    grouped = df.groupby("animalId")
    for aid, group in grouped:
        n_ticks = len(group)
        if n_ticks >= SEQ_LEN:
            total_seqs += (n_ticks - SEQ_LEN) // STRIDE + 1
            
    logger.info(f"Preallocating contiguous memory for {total_seqs} sequences to prevent OOM...")
    
    # Strictly Pre-allocate (avoid list appending fragmentation)
    X = np.zeros((total_seqs, SEQ_LEN, len(feature_cols)), dtype=np.float32)
    Y = np.zeros((total_seqs, len(target_cols)), dtype=np.float32)
    
    processed = 0
    total = len(grouped)
    seq_idx = 0
    
    for aid, group in grouped:
        processed += 1
        if processed % 25 == 0:
            logger.info(f"  Sliced {processed}/{total} sub-trajectories...")
            
        group = group.sort_values("timestamp")
        
        features_arr = group[feature_cols].values
        targets_arr = group[target_cols].values
        
        n_ticks = len(features_arr)
        if n_ticks < SEQ_LEN:
            continue
            
        # Strided sliding window
        for start_idx in range(0, n_ticks - SEQ_LEN + 1, STRIDE):
            end_idx = start_idx + SEQ_LEN
            
            X[seq_idx] = features_arr[start_idx:end_idx]
            Y[seq_idx] = targets_arr[end_idx - 1]
            seq_idx += 1
    
    logger.info(f"Final Tensor Shape: X={X.shape}, Y={Y.shape}")
    
    np.save(os.path.join(DATA_DIR, "v11_X_sequences.npy"), X)
    np.save(os.path.join(DATA_DIR, "v11_Y_targets.npy"), Y)
    
    logger.info("Sequence extraction complete.")

def main():
    start = time.time()
    logger.info("=" * 60)
    logger.info("🔄 Phase 12 — Sequence Feature Extractor v11")
    logger.info("=" * 60)
    
    df_flat = build_flat_timeseries()
    df_features, feature_cols, target_cols = compute_multimodal_features(df_flat)
    
    # df_features.to_csv(os.path.join(DATA_DIR, "v11_flat_features.csv"), index=False)
    
    extract_pytorch_sequences(df_features, feature_cols, target_cols)
    
    logger.info(f"✅ V11 Feature Pipeline Done in {time.time() - start:.1f}s")

if __name__ == "__main__":
    main()
